
package ar.com.osde.sujetovip.backend.services.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ar.com.osde.sujetovip.services.ObjectFactory;
import ar.com.osde.sujetovip.services.ProcessResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UpdateSocioVipRegistryService", targetNamespace = "http://services.sujetovip.osde.com.ar/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UpdateSocioVipRegistryService {


    /**
     * 
     * @param arg0
     * @return
     *     returns ar.com.osde.sujetovip.services.ProcessResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancel", targetNamespace = "http://services.sujetovip.osde.com.ar/", className = "ar.com.osde.sujetovip.services.Cancel")
    @ResponseWrapper(localName = "cancelResponse", targetNamespace = "http://services.sujetovip.osde.com.ar/", className = "ar.com.osde.sujetovip.services.CancelResponse")
    public ProcessResponse cancel(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns ar.com.osde.sujetovip.services.ProcessResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "start", targetNamespace = "http://services.sujetovip.osde.com.ar/", className = "ar.com.osde.sujetovip.services.Start")
    @ResponseWrapper(localName = "startResponse", targetNamespace = "http://services.sujetovip.osde.com.ar/", className = "ar.com.osde.sujetovip.services.StartResponse")
    public ProcessResponse start();

    /**
     * 
     * @param arg0
     * @return
     *     returns ar.com.osde.sujetovip.services.ProcessResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "status", targetNamespace = "http://services.sujetovip.osde.com.ar/", className = "ar.com.osde.sujetovip.services.Status")
    @ResponseWrapper(localName = "statusResponse", targetNamespace = "http://services.sujetovip.osde.com.ar/", className = "ar.com.osde.sujetovip.services.StatusResponse")
    public ProcessResponse status(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
