
package ar.com.osde.sujetovip.backend.services.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UpdateSocioVipRegistryService", targetNamespace = "http://impl.services.backend.sujetovip.osde.com.ar/", wsdlLocation = "http://sujetosvipt.intranet.osde:8680/sujetovip-backend/webservices/UpdateSocioVipRegistryService?wsdl")
public class UpdateSocioVipRegistryService_Service
    extends Service
{

    private final static URL UPDATESOCIOVIPREGISTRYSERVICE_WSDL_LOCATION;
    private final static WebServiceException UPDATESOCIOVIPREGISTRYSERVICE_EXCEPTION;
    private final static QName UPDATESOCIOVIPREGISTRYSERVICE_QNAME = new QName("http://impl.services.backend.sujetovip.osde.com.ar/", "UpdateSocioVipRegistryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sujetosvipt.intranet.osde:8680/sujetovip-backend/webservices/UpdateSocioVipRegistryService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UPDATESOCIOVIPREGISTRYSERVICE_WSDL_LOCATION = url;
        UPDATESOCIOVIPREGISTRYSERVICE_EXCEPTION = e;
    }

    public UpdateSocioVipRegistryService_Service() {
        super(__getWsdlLocation(), UPDATESOCIOVIPREGISTRYSERVICE_QNAME);
    }

    public UpdateSocioVipRegistryService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), UPDATESOCIOVIPREGISTRYSERVICE_QNAME, features);
    }

    public UpdateSocioVipRegistryService_Service(URL wsdlLocation) {
        super(wsdlLocation, UPDATESOCIOVIPREGISTRYSERVICE_QNAME);
    }

    public UpdateSocioVipRegistryService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UPDATESOCIOVIPREGISTRYSERVICE_QNAME, features);
    }

    public UpdateSocioVipRegistryService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UpdateSocioVipRegistryService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UpdateSocioVipRegistryService
     */
    @WebEndpoint(name = "UpdateSocioVipRegistryServiceImplPort")
    public UpdateSocioVipRegistryService getUpdateSocioVipRegistryServiceImplPort() {
        return super.getPort(new QName("http://impl.services.backend.sujetovip.osde.com.ar/", "UpdateSocioVipRegistryServiceImplPort"), UpdateSocioVipRegistryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpdateSocioVipRegistryService
     */
    @WebEndpoint(name = "UpdateSocioVipRegistryServiceImplPort")
    public UpdateSocioVipRegistryService getUpdateSocioVipRegistryServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.services.backend.sujetovip.osde.com.ar/", "UpdateSocioVipRegistryServiceImplPort"), UpdateSocioVipRegistryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UPDATESOCIOVIPREGISTRYSERVICE_EXCEPTION!= null) {
            throw UPDATESOCIOVIPREGISTRYSERVICE_EXCEPTION;
        }
        return UPDATESOCIOVIPREGISTRYSERVICE_WSDL_LOCATION;
    }

}
